CREATE TABLE [Role](
	Id INT PRIMARY KEY IDENTITY (1,1),
	[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE [User](
	Id INT PRIMARY KEY IDENTITY (1,1),
    RoleId INT REFERENCES [Role](Id) NOT NULL, 
    Username VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Gender VARCHAR(50) NOT NULL,
    [Password] VARCHAR(50) NOT NULL,
)

CREATE TABLE [Meat](
	Id INT PRIMARY KEY IDENTITY (1,1),
    [Name] VARCHAR(50)
)

CREATE TABLE [Header](
	Id INT PRIMARY KEY IDENTITY (1,1),
    CustomerId INT REFERENCES [User](Id) NOT NULL,
    StaffId INT NOT NULL,
    [Date] DATE
)

CREATE TABLE [Ramen](
	Id INT PRIMARY KEY IDENTITY(1,1),
    MeatId INT REFERENCES [Meat](Id) NOT NULL,
    [Name] VARCHAR(50) NOT NULL,
    Broth VARCHAR(50) NOT NULL,
    Price VARCHAR(50) NOT NULL
)

CREATE TABLE [Detail](
	HeaderId INT REFERENCES [Header](Id) NOT NULL,
    RamenId INT REFERENCES [Ramen](Id) NOT NULL,
    Quantity INT NOT NULL,

    PRIMARY KEY(HeaderId, RamenId)
)